services:
  - type: web
    name: benchaura-server
    runtime: node
    region: oregon
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: CLIENT_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
